/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class Chars {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Chars(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Chars obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_Chars(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Chars(int n) {
    this(graph2dJNI.new_Chars(n), true);
  }

  public int count() {
    return graph2dJNI.Chars_count(swigCPtr, this);
  }

  public char get(int index) {
    return graph2dJNI.Chars_get(swigCPtr, this, index);
  }

  public void set(int index, char value) {
    graph2dJNI.Chars_set(swigCPtr, this, index, value);
  }

}
