/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class graph2d {
  public static MgShapes mgCreateShapes(MgObject owner, int index) {
    long cPtr = graph2dJNI.mgCreateShapes__SWIG_0(MgObject.getCPtr(owner), owner, index);
    return (cPtr == 0) ? null : new MgShapes(cPtr, false);
  }

  public static MgShapes mgCreateShapes(MgObject owner) {
    long cPtr = graph2dJNI.mgCreateShapes__SWIG_1(MgObject.getCPtr(owner), owner);
    return (cPtr == 0) ? null : new MgShapes(cPtr, false);
  }

  public static MgShapes mgCreateShapes() {
    long cPtr = graph2dJNI.mgCreateShapes__SWIG_2();
    return (cPtr == 0) ? null : new MgShapes(cPtr, false);
  }

}
