/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgEllipse extends MgBaseRect {
  private long swigCPtr;

  protected MgEllipse(long cPtr, boolean cMemoryOwn) {
    super(graph2dJNI.MgEllipse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgEllipse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_MgEllipse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MgEllipse() {
    this(graph2dJNI.new_MgEllipse(), true);
  }

  public static MgEllipse create() {
    long cPtr = graph2dJNI.MgEllipse_create();
    return (cPtr == 0) ? null : new MgEllipse(cPtr, false);
  }

  public static int Type() {
    return graph2dJNI.MgEllipse_Type();
  }

  public float getRadiusX() {
    return graph2dJNI.MgEllipse_getRadiusX(swigCPtr, this);
  }

  public float getRadiusY() {
    return graph2dJNI.MgEllipse_getRadiusY(swigCPtr, this);
  }

  public void setRadius(float rx, float ry) {
    graph2dJNI.MgEllipse_setRadius__SWIG_0(swigCPtr, this, rx, ry);
  }

  public void setRadius(float rx) {
    graph2dJNI.MgEllipse_setRadius__SWIG_1(swigCPtr, this, rx);
  }

}
