/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgJsonStorage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgJsonStorage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgJsonStorage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_MgJsonStorage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MgJsonStorage() {
    this(graph2dJNI.new_MgJsonStorage(), true);
  }

  public MgStorage storageForRead(String content) {
    long cPtr = graph2dJNI.MgJsonStorage_storageForRead(swigCPtr, this, content);
    return (cPtr == 0) ? null : new MgStorage(cPtr, false);
  }

  public MgStorage storageForWrite() {
    long cPtr = graph2dJNI.MgJsonStorage_storageForWrite(swigCPtr, this);
    return (cPtr == 0) ? null : new MgStorage(cPtr, false);
  }

  public String stringify(boolean pretty) {
    return graph2dJNI.MgJsonStorage_stringify(swigCPtr, this, pretty);
  }

  public String getParseError() {
    return graph2dJNI.MgJsonStorage_getParseError(swigCPtr, this);
  }

}
