/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgLockRW {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgLockRW(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgLockRW obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_MgLockRW(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MgLockRW() {
    this(graph2dJNI.new_MgLockRW(), true);
  }

  public boolean lock(boolean forWrite, int timeout) {
    return graph2dJNI.MgLockRW_lock__SWIG_0(swigCPtr, this, forWrite, timeout);
  }

  public boolean lock(boolean forWrite) {
    return graph2dJNI.MgLockRW_lock__SWIG_1(swigCPtr, this, forWrite);
  }

  public int unlock(boolean forWrite) {
    return graph2dJNI.MgLockRW_unlock(swigCPtr, this, forWrite);
  }

  public boolean firstLocked() {
    return graph2dJNI.MgLockRW_firstLocked(swigCPtr, this);
  }

  public boolean lockedForRead() {
    return graph2dJNI.MgLockRW_lockedForRead(swigCPtr, this);
  }

  public boolean lockedForWrite() {
    return graph2dJNI.MgLockRW_lockedForWrite(swigCPtr, this);
  }

  public int getEditFlags() {
    return graph2dJNI.MgLockRW_getEditFlags(swigCPtr, this);
  }

  public void setEditFlags(int flags) {
    graph2dJNI.MgLockRW_setEditFlags(swigCPtr, this, flags);
  }

}
