/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgShapes extends MgObject {
  private long swigCPtr;

  protected MgShapes(long cPtr, boolean cMemoryOwn) {
    super(graph2dJNI.MgShapes_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgShapes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static int Type() {
    return graph2dJNI.MgShapes_Type();
  }

  public MgShapes cloneShapes() {
    long cPtr = graph2dJNI.MgShapes_cloneShapes(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShapes(cPtr, false);
  }

  public int getShapeCount() {
    return graph2dJNI.MgShapes_getShapeCount(swigCPtr, this);
  }

  public MgShape getHeadShape() {
    long cPtr = graph2dJNI.MgShapes_getHeadShape(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape getLastShape() {
    long cPtr = graph2dJNI.MgShapes_getLastShape(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape findShape(int sid) {
    long cPtr = graph2dJNI.MgShapes_findShape(swigCPtr, this, sid);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape findShapeByTag(int tag) {
    long cPtr = graph2dJNI.MgShapes_findShapeByTag(swigCPtr, this, tag);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape findShapeByType(int type) {
    long cPtr = graph2dJNI.MgShapes_findShapeByType(swigCPtr, this, type);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public Box2d getExtent() {
    return new Box2d(graph2dJNI.MgShapes_getExtent(swigCPtr, this), true);
  }

  public MgShape hitTest(Box2d limits, Point2d nearpt) {
    long cPtr = graph2dJNI.MgShapes_hitTest(swigCPtr, this, Box2d.getCPtr(limits), limits, Point2d.getCPtr(nearpt), nearpt);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public int draw(GiGraphics gs, GiContext ctx) {
    return graph2dJNI.MgShapes_draw__SWIG_0(swigCPtr, this, GiGraphics.getCPtr(gs), gs, GiContext.getCPtr(ctx), ctx);
  }

  public int draw(GiGraphics gs) {
    return graph2dJNI.MgShapes_draw__SWIG_1(swigCPtr, this, GiGraphics.getCPtr(gs), gs);
  }

  public int dyndraw(int mode, GiGraphics gs, GiContext ctx, int segment) {
    return graph2dJNI.MgShapes_dyndraw(swigCPtr, this, mode, GiGraphics.getCPtr(gs), gs, GiContext.getCPtr(ctx), ctx, segment);
  }

  public boolean save(MgStorage s, int startIndex) {
    return graph2dJNI.MgShapes_save__SWIG_0(swigCPtr, this, MgStorage.getCPtr(s), s, startIndex);
  }

  public boolean save(MgStorage s) {
    return graph2dJNI.MgShapes_save__SWIG_1(swigCPtr, this, MgStorage.getCPtr(s), s);
  }

  public boolean load(MgStorage s, boolean addOnly) {
    return graph2dJNI.MgShapes_load__SWIG_0(swigCPtr, this, MgStorage.getCPtr(s), s, addOnly);
  }

  public boolean load(MgStorage s) {
    return graph2dJNI.MgShapes_load__SWIG_1(swigCPtr, this, MgStorage.getCPtr(s), s);
  }

  public void clear() {
    graph2dJNI.MgShapes_clear(swigCPtr, this);
  }

  public void copyShapes(MgShapes src) {
    graph2dJNI.MgShapes_copyShapes(swigCPtr, this, MgShapes.getCPtr(src), src);
  }

  public MgShape addShape(MgShape src) {
    long cPtr = graph2dJNI.MgShapes_addShape(swigCPtr, this, MgShape.getCPtr(src), src);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape addShapeByType(int type) {
    long cPtr = graph2dJNI.MgShapes_addShapeByType(swigCPtr, this, type);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape removeShape(int sid) {
    long cPtr = graph2dJNI.MgShapes_removeShape(swigCPtr, this, sid);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public MgShape moveTo(int sid, MgShapes dest) {
    long cPtr = graph2dJNI.MgShapes_moveTo(swigCPtr, this, sid, MgShapes.getCPtr(dest), dest);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public void moveAllShapesTo(MgShapes dest) {
    graph2dJNI.MgShapes_moveAllShapesTo(swigCPtr, this, MgShapes.getCPtr(dest), dest);
  }

  public boolean bringToFront(int sid) {
    return graph2dJNI.MgShapes_bringToFront(swigCPtr, this, sid);
  }

  public MgObject getOwner() {
    long cPtr = graph2dJNI.MgShapes_getOwner(swigCPtr, this);
    return (cPtr == 0) ? null : new MgObject(cPtr, false);
  }

}
