/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgShape extends MgObject {
  private long swigCPtr;

  protected MgShape(long cPtr, boolean cMemoryOwn) {
    super(graph2dJNI.MgShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static int Type() {
    return graph2dJNI.MgShape_Type();
  }

  public MgShape cloneShape() {
    long cPtr = graph2dJNI.MgShape_cloneShape(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

  public GiContext context() {
    long cPtr = graph2dJNI.MgShape_context(swigCPtr, this);
    return (cPtr == 0) ? null : new GiContext(cPtr, false);
  }

  public GiContext contextc() {
    long cPtr = graph2dJNI.MgShape_contextc(swigCPtr, this);
    return (cPtr == 0) ? null : new GiContext(cPtr, false);
  }

  public MgBaseShape shape() {
    long cPtr = graph2dJNI.MgShape_shape(swigCPtr, this);
    return (cPtr == 0) ? null : new MgBaseShape(cPtr, false);
  }

  public MgBaseShape shapec() {
    long cPtr = graph2dJNI.MgShape_shapec(swigCPtr, this);
    return (cPtr == 0) ? null : new MgBaseShape(cPtr, false);
  }

  public boolean draw(int mode, GiGraphics gs, GiContext ctx, int segment) {
    return graph2dJNI.MgShape_draw__SWIG_0(swigCPtr, this, mode, GiGraphics.getCPtr(gs), gs, GiContext.getCPtr(ctx), ctx, segment);
  }

  public boolean draw(int mode, GiGraphics gs, GiContext ctx) {
    return graph2dJNI.MgShape_draw__SWIG_1(swigCPtr, this, mode, GiGraphics.getCPtr(gs), gs, GiContext.getCPtr(ctx), ctx);
  }

  public boolean draw(int mode, GiGraphics gs) {
    return graph2dJNI.MgShape_draw__SWIG_2(swigCPtr, this, mode, GiGraphics.getCPtr(gs), gs);
  }

  public boolean save(MgStorage s) {
    return graph2dJNI.MgShape_save(swigCPtr, this, MgStorage.getCPtr(s), s);
  }

  public boolean load(MgStorage s) {
    return graph2dJNI.MgShape_load(swigCPtr, this, MgStorage.getCPtr(s), s);
  }

  public int getID() {
    return graph2dJNI.MgShape_getID(swigCPtr, this);
  }

  public MgShapes getParent() {
    long cPtr = graph2dJNI.MgShape_getParent(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShapes(cPtr, false);
  }

  public void setParent(MgShapes p, int sid) {
    graph2dJNI.MgShape_setParent(swigCPtr, this, MgShapes.getCPtr(p), p, sid);
  }

  public int getTag() {
    return graph2dJNI.MgShape_getTag(swigCPtr, this);
  }

  public void setTag(int tag) {
    graph2dJNI.MgShape_setTag(swigCPtr, this, tag);
  }

}
