/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgSplines extends MgBaseLines {
  private long swigCPtr;

  protected MgSplines(long cPtr, boolean cMemoryOwn) {
    super(graph2dJNI.MgSplines_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgSplines obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_MgSplines(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MgSplines() {
    this(graph2dJNI.new_MgSplines(), true);
  }

  public static MgSplines create() {
    long cPtr = graph2dJNI.MgSplines_create();
    return (cPtr == 0) ? null : new MgSplines(cPtr, false);
  }

  public static int Type() {
    return graph2dJNI.MgSplines_Type();
  }

  public void smooth(float tol) {
    graph2dJNI.MgSplines_smooth(swigCPtr, this, tol);
  }

}
