/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgStorage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgStorage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgStorage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_MgStorage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean readNode(String name, int index, boolean ended) {
    return graph2dJNI.MgStorage_readNode(swigCPtr, this, name, index, ended);
  }

  public boolean writeNode(String name, int index, boolean ended) {
    return graph2dJNI.MgStorage_writeNode(swigCPtr, this, name, index, ended);
  }

  public boolean readBool(String name, boolean defvalue) {
    return graph2dJNI.MgStorage_readBool(swigCPtr, this, name, defvalue);
  }

  public float readFloat(String name, float defvalue) {
    return graph2dJNI.MgStorage_readFloat(swigCPtr, this, name, defvalue);
  }

  public void writeBool(String name, boolean value) {
    graph2dJNI.MgStorage_writeBool(swigCPtr, this, name, value);
  }

  public void writeFloat(String name, float value) {
    graph2dJNI.MgStorage_writeFloat(swigCPtr, this, name, value);
  }

  public void writeString(String name, String value) {
    graph2dJNI.MgStorage_writeString(swigCPtr, this, name, value);
  }

  public int readInt(String name, int defvalue) {
    return graph2dJNI.MgStorage_readInt(swigCPtr, this, name, defvalue);
  }

  public void writeInt(String name, int value) {
    graph2dJNI.MgStorage_writeInt(swigCPtr, this, name, value);
  }

  public void writeUInt(String name, int value) {
    graph2dJNI.MgStorage_writeUInt(swigCPtr, this, name, value);
  }

  public boolean setError(String arg0) {
    return graph2dJNI.MgStorage_setError(swigCPtr, this, arg0);
  }

}
