/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class Tol {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Tol(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Tol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        graph2dJNI.delete_Tol(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Tol gTol() {
    return new Tol(graph2dJNI.Tol_gTol(), false);
  }

  public static Tol minTol() {
    return new Tol(graph2dJNI.Tol_minTol(), false);
  }

  public Tol() {
    this(graph2dJNI.new_Tol__SWIG_0(), true);
  }

  public Tol(float tolPoint, float tolVector) {
    this(graph2dJNI.new_Tol__SWIG_1(tolPoint, tolVector), true);
  }

  public Tol(float tolPoint) {
    this(graph2dJNI.new_Tol__SWIG_2(tolPoint), true);
  }

  public float equalPoint() {
    return graph2dJNI.Tol_equalPoint(swigCPtr, this);
  }

  public float equalVector() {
    return graph2dJNI.Tol_equalVector(swigCPtr, this);
  }

  public void setEqualPoint(float tol) {
    graph2dJNI.Tol_setEqualPoint(swigCPtr, this, tol);
  }

  public void setEqualVector(float tol) {
    graph2dJNI.Tol_setEqualVector(swigCPtr, this, tol);
  }

}
