/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_skiaview_WRAP_H_
#define SWIG_skiaview_WRAP_H_

class SwigDirector_GiCanvasBase : public GiCanvasBase, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_GiCanvasBase(JNIEnv *jenv);
    virtual ~SwigDirector_GiCanvasBase();
    virtual float getScreenDpi() const;
    virtual GiColor getBkColor() const;
    virtual GiColor setBkColor(GiColor const &color);
    virtual void setNeedRedraw();
    virtual bool drawHandle(float x, float y, int index);
    virtual void penChanged(int argb, float penWidth, int lineStyle);
    virtual void brushChanged(int argb);
    virtual bool isContextActionsVisible();
    virtual bool showContextActions(mgvector< int > const &actions, float x, float y, float w, float h);
    virtual bool drawLine(float x1, float y1, float x2, float y2);
    virtual bool drawLines(mgvector< float > const &pxs);
    virtual bool drawBeziers(mgvector< float > const &pxs);
    virtual bool drawPolygon(mgvector< float > const &pxs, bool stroke, bool fill);
    virtual bool drawRect(float x, float y, float w, float h, bool stroke, bool fill);
    virtual bool drawEllipse(float x, float y, float w, float h, bool stroke, bool fill);
    virtual bool beginPath();
    virtual bool moveTo(float x, float y);
    virtual bool lineTo(float x, float y);
    virtual bool bezierTo(float c1x, float c1y, float c2x, float c2y, float x, float y);
    virtual bool closePath();
    virtual bool endPath(bool stroke, bool fill);
    virtual void clearWindow();
    virtual void clearCachedBitmap(bool clearAll = false);
    virtual bool drawCachedBitmap(float x = 0, float y = 0, bool secondBmp = false);
    virtual void saveCachedBitmap(bool secondBmp = false);
    virtual bool hasCachedBitmap(bool secondBmp = false) const;
    virtual bool isBufferedDrawing() const;
    virtual void clipBoxChanged(float x, float y, float w, float h);
    virtual void antiAliasModeChanged(bool antiAlias);
    virtual bool drawImage(char const *name, float xc, float yc, float w, float h, float angle);
    virtual void rawTextCenter(char const *text, float x, float y, float h);
public:
    bool swig_overrides(int n) {
      return (n < 37 ? swig_override[n] : false);
    }
protected:
    bool swig_override[37];
};


#endif
