#!/bin/sh
# Type 'sh swig.sh' to make src/jni/*.java and libgraph2d.so for Android.
#
python utf8togbk.py # the swig application don't support UTF8 files.
cd graph2d/jni

mkdir ../src/touchvg/jni
rm -rf ../src/touchvg/jni/*.*
swig -c++ -java -package touchvg.jni \
    -outdir ../src/touchvg/jni \
    -o graph2d_java_wrap.cpp \
    -I../../../core/include/geom \
    -I../../../core/include/graph \
    -I../../../core/include/shape \
    graph2d.swig

python replacejstr.py # fix code lines generated by swig

ndk-build
cd ../..
python restore_utf8.py
