/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.core;

public class CmdObserverDefault extends CmdObserver {
  private long swigCPtr;

  protected CmdObserverDefault(long cPtr, boolean cMemoryOwn) {
    super(touchvgJNI.CmdObserverDefault_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CmdObserverDefault obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_CmdObserverDefault(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    touchvgJNI.CmdObserverDefault_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    touchvgJNI.CmdObserverDefault_change_ownership(this, swigCPtr, true);
  }

  public CmdObserverDefault() {
    this(touchvgJNI.new_CmdObserverDefault(), true);
    touchvgJNI.CmdObserverDefault_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void onDocLoaded(MgMotion arg0) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_onDocLoaded(swigCPtr, this, MgMotion.getCPtr(arg0), arg0); else touchvgJNI.CmdObserverDefault_onDocLoadedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0);
  }

  public void onEnterSelectCommand(MgMotion arg0) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_onEnterSelectCommand(swigCPtr, this, MgMotion.getCPtr(arg0), arg0); else touchvgJNI.CmdObserverDefault_onEnterSelectCommandSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0);
  }

  public void onUnloadCommands(MgCmdManager arg0) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_onUnloadCommands(swigCPtr, this, MgCmdManager.getCPtr(arg0), arg0); else touchvgJNI.CmdObserverDefault_onUnloadCommandsSwigExplicitCmdObserverDefault(swigCPtr, this, MgCmdManager.getCPtr(arg0), arg0);
  }

  public boolean selectActionsNeedHided(MgMotion arg0) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_selectActionsNeedHided(swigCPtr, this, MgMotion.getCPtr(arg0), arg0) : touchvgJNI.CmdObserverDefault_selectActionsNeedHidedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0);
  }

  public boolean doAction(MgMotion arg0, int arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_doAction(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, arg1) : touchvgJNI.CmdObserverDefault_doActionSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, arg1);
  }

  public boolean doEndAction(MgMotion arg0, int arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_doEndAction(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, arg1) : touchvgJNI.CmdObserverDefault_doEndActionSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, arg1);
  }

  public void drawInShapeCommand(MgMotion arg0, MgCommand arg1, GiGraphics arg2) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_drawInShapeCommand(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgCommand.getCPtr(arg1), arg1, GiGraphics.getCPtr(arg2), arg2); else touchvgJNI.CmdObserverDefault_drawInShapeCommandSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgCommand.getCPtr(arg1), arg1, GiGraphics.getCPtr(arg2), arg2);
  }

  public void drawInSelectCommand(MgMotion arg0, MgShape arg1, int arg2, GiGraphics arg3) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_drawInSelectCommand(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1, arg2, GiGraphics.getCPtr(arg3), arg3); else touchvgJNI.CmdObserverDefault_drawInSelectCommandSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1, arg2, GiGraphics.getCPtr(arg3), arg3);
  }

  public boolean onShapeWillAdded(MgMotion arg0, MgShape arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_onShapeWillAdded(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1) : touchvgJNI.CmdObserverDefault_onShapeWillAddedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public void onShapeAdded(MgMotion arg0, MgShape arg1) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_onShapeAdded(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1); else touchvgJNI.CmdObserverDefault_onShapeAddedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public boolean onShapeWillDeleted(MgMotion arg0, MgShape arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_onShapeWillDeleted(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1) : touchvgJNI.CmdObserverDefault_onShapeWillDeletedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public void onShapeDeleted(MgMotion arg0, MgShape arg1) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_onShapeDeleted(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1); else touchvgJNI.CmdObserverDefault_onShapeDeletedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public boolean onShapeCanRotated(MgMotion arg0, MgShape arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_onShapeCanRotated(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1) : touchvgJNI.CmdObserverDefault_onShapeCanRotatedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public boolean onShapeCanTransform(MgMotion arg0, MgShape arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_onShapeCanTransform(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1) : touchvgJNI.CmdObserverDefault_onShapeCanTransformSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public boolean onShapeCanUnlock(MgMotion arg0, MgShape arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_onShapeCanUnlock(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1) : touchvgJNI.CmdObserverDefault_onShapeCanUnlockSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public boolean onShapeCanUngroup(MgMotion arg0, MgShape arg1) {
    return (getClass() == CmdObserverDefault.class) ? touchvgJNI.CmdObserverDefault_onShapeCanUngroup(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1) : touchvgJNI.CmdObserverDefault_onShapeCanUngroupSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1);
  }

  public void onShapeMoved(MgMotion arg0, MgShape arg1, int arg2) {
    if (getClass() == CmdObserverDefault.class) touchvgJNI.CmdObserverDefault_onShapeMoved(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1, arg2); else touchvgJNI.CmdObserverDefault_onShapeMovedSwigExplicitCmdObserverDefault(swigCPtr, this, MgMotion.getCPtr(arg0), arg0, MgShape.getCPtr(arg1), arg1, arg2);
  }

}
