/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.core;

public class MgBasicShapes {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgBasicShapes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgBasicShapes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_MgBasicShapes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void registerShapes(MgShapeFactory factory) {
    touchvgJNI.MgBasicShapes_registerShapes(MgShapeFactory.getCPtr(factory), factory);
  }

  public MgBasicShapes() {
    this(touchvgJNI.new_MgBasicShapes(), true);
  }

}
