/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class GiCanvasBase {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GiCanvasBase(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GiCanvasBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_GiCanvasBase(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    skiaviewJNI.GiCanvasBase_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    skiaviewJNI.GiCanvasBase_change_ownership(this, swigCPtr, true);
  }

  public GiCanvasBase() {
    this(skiaviewJNI.new_GiCanvasBase(), true);
    skiaviewJNI.GiCanvasBase_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public GiTransform xf() {
    return new GiTransform(skiaviewJNI.GiCanvasBase_xf(swigCPtr, this), false);
  }

  public GiGraphics gs() {
    return new GiGraphics(skiaviewJNI.GiCanvasBase_gs(swigCPtr, this), false);
  }

  public static void setScreenDpi(float dpi) {
    skiaviewJNI.GiCanvasBase_setScreenDpi(dpi);
  }

  public float getScreenDpi() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_getScreenDpi(swigCPtr, this) : skiaviewJNI.GiCanvasBase_getScreenDpiSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public GiColor getBkColor() {
    return new GiColor((getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_getBkColor(swigCPtr, this) : skiaviewJNI.GiCanvasBase_getBkColorSwigExplicitGiCanvasBase(swigCPtr, this), true);
  }

  public GiColor setBkColor(GiColor color) {
    return new GiColor((getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_setBkColor(swigCPtr, this, GiColor.getCPtr(color), color) : skiaviewJNI.GiCanvasBase_setBkColorSwigExplicitGiCanvasBase(swigCPtr, this, GiColor.getCPtr(color), color), true);
  }

  public boolean beginPaint() {
    return skiaviewJNI.GiCanvasBase_beginPaint(swigCPtr, this);
  }

  public void endPaint() {
    skiaviewJNI.GiCanvasBase_endPaint(swigCPtr, this);
  }

  public void setNeedRedraw() {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_setNeedRedraw(swigCPtr, this); else skiaviewJNI.GiCanvasBase_setNeedRedrawSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public boolean drawHandle(float x, float y, int index) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawHandle(swigCPtr, this, x, y, index) : skiaviewJNI.GiCanvasBase_drawHandleSwigExplicitGiCanvasBase(swigCPtr, this, x, y, index);
  }

  public void penChanged(int argb, float penWidth, int lineStyle) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_penChanged(swigCPtr, this, argb, penWidth, lineStyle); else skiaviewJNI.GiCanvasBase_penChangedSwigExplicitGiCanvasBase(swigCPtr, this, argb, penWidth, lineStyle);
  }

  public void brushChanged(int argb) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_brushChanged(swigCPtr, this, argb); else skiaviewJNI.GiCanvasBase_brushChangedSwigExplicitGiCanvasBase(swigCPtr, this, argb);
  }

  public boolean isContextActionsVisible() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_isContextActionsVisible(swigCPtr, this) : skiaviewJNI.GiCanvasBase_isContextActionsVisibleSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public boolean showContextActions(Ints actions, float x, float y, float w, float h) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_showContextActions(swigCPtr, this, Ints.getCPtr(actions), actions, x, y, w, h) : skiaviewJNI.GiCanvasBase_showContextActionsSwigExplicitGiCanvasBase(swigCPtr, this, Ints.getCPtr(actions), actions, x, y, w, h);
  }

  public boolean drawLine(float x1, float y1, float x2, float y2) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawLine(swigCPtr, this, x1, y1, x2, y2) : skiaviewJNI.GiCanvasBase_drawLineSwigExplicitGiCanvasBase(swigCPtr, this, x1, y1, x2, y2);
  }

  public boolean drawLines(Floats pxs) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawLines(swigCPtr, this, Floats.getCPtr(pxs), pxs) : skiaviewJNI.GiCanvasBase_drawLinesSwigExplicitGiCanvasBase(swigCPtr, this, Floats.getCPtr(pxs), pxs);
  }

  public boolean drawBeziers(Floats pxs) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawBeziers(swigCPtr, this, Floats.getCPtr(pxs), pxs) : skiaviewJNI.GiCanvasBase_drawBeziersSwigExplicitGiCanvasBase(swigCPtr, this, Floats.getCPtr(pxs), pxs);
  }

  public boolean drawPolygon(Floats pxs, boolean stroke, boolean fill) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawPolygon(swigCPtr, this, Floats.getCPtr(pxs), pxs, stroke, fill) : skiaviewJNI.GiCanvasBase_drawPolygonSwigExplicitGiCanvasBase(swigCPtr, this, Floats.getCPtr(pxs), pxs, stroke, fill);
  }

  public boolean drawRect(float x, float y, float w, float h, boolean stroke, boolean fill) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawRect(swigCPtr, this, x, y, w, h, stroke, fill) : skiaviewJNI.GiCanvasBase_drawRectSwigExplicitGiCanvasBase(swigCPtr, this, x, y, w, h, stroke, fill);
  }

  public boolean drawEllipse(float x, float y, float w, float h, boolean stroke, boolean fill) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawEllipse(swigCPtr, this, x, y, w, h, stroke, fill) : skiaviewJNI.GiCanvasBase_drawEllipseSwigExplicitGiCanvasBase(swigCPtr, this, x, y, w, h, stroke, fill);
  }

  public boolean beginPath() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_beginPath(swigCPtr, this) : skiaviewJNI.GiCanvasBase_beginPathSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public boolean moveTo(float x, float y) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_moveTo(swigCPtr, this, x, y) : skiaviewJNI.GiCanvasBase_moveToSwigExplicitGiCanvasBase(swigCPtr, this, x, y);
  }

  public boolean lineTo(float x, float y) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_lineTo(swigCPtr, this, x, y) : skiaviewJNI.GiCanvasBase_lineToSwigExplicitGiCanvasBase(swigCPtr, this, x, y);
  }

  public boolean bezierTo(float c1x, float c1y, float c2x, float c2y, float x, float y) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_bezierTo(swigCPtr, this, c1x, c1y, c2x, c2y, x, y) : skiaviewJNI.GiCanvasBase_bezierToSwigExplicitGiCanvasBase(swigCPtr, this, c1x, c1y, c2x, c2y, x, y);
  }

  public boolean closePath() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_closePath(swigCPtr, this) : skiaviewJNI.GiCanvasBase_closePathSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public boolean endPath(boolean stroke, boolean fill) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_endPath(swigCPtr, this, stroke, fill) : skiaviewJNI.GiCanvasBase_endPathSwigExplicitGiCanvasBase(swigCPtr, this, stroke, fill);
  }

  public void clearWindow() {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_clearWindow(swigCPtr, this); else skiaviewJNI.GiCanvasBase_clearWindowSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public void clearCachedBitmap(boolean clearAll) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_clearCachedBitmap__SWIG_0(swigCPtr, this, clearAll); else skiaviewJNI.GiCanvasBase_clearCachedBitmapSwigExplicitGiCanvasBase__SWIG_0(swigCPtr, this, clearAll);
  }

  public void clearCachedBitmap() {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_clearCachedBitmap__SWIG_1(swigCPtr, this); else skiaviewJNI.GiCanvasBase_clearCachedBitmapSwigExplicitGiCanvasBase__SWIG_1(swigCPtr, this);
  }

  public boolean drawCachedBitmap(float x, float y, boolean secondBmp) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawCachedBitmap__SWIG_0(swigCPtr, this, x, y, secondBmp) : skiaviewJNI.GiCanvasBase_drawCachedBitmapSwigExplicitGiCanvasBase__SWIG_0(swigCPtr, this, x, y, secondBmp);
  }

  public boolean drawCachedBitmap(float x, float y) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawCachedBitmap__SWIG_1(swigCPtr, this, x, y) : skiaviewJNI.GiCanvasBase_drawCachedBitmapSwigExplicitGiCanvasBase__SWIG_1(swigCPtr, this, x, y);
  }

  public boolean drawCachedBitmap(float x) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawCachedBitmap__SWIG_2(swigCPtr, this, x) : skiaviewJNI.GiCanvasBase_drawCachedBitmapSwigExplicitGiCanvasBase__SWIG_2(swigCPtr, this, x);
  }

  public boolean drawCachedBitmap() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawCachedBitmap__SWIG_3(swigCPtr, this) : skiaviewJNI.GiCanvasBase_drawCachedBitmapSwigExplicitGiCanvasBase__SWIG_3(swigCPtr, this);
  }

  public void saveCachedBitmap(boolean secondBmp) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_saveCachedBitmap__SWIG_0(swigCPtr, this, secondBmp); else skiaviewJNI.GiCanvasBase_saveCachedBitmapSwigExplicitGiCanvasBase__SWIG_0(swigCPtr, this, secondBmp);
  }

  public void saveCachedBitmap() {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_saveCachedBitmap__SWIG_1(swigCPtr, this); else skiaviewJNI.GiCanvasBase_saveCachedBitmapSwigExplicitGiCanvasBase__SWIG_1(swigCPtr, this);
  }

  public boolean hasCachedBitmap(boolean secondBmp) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_hasCachedBitmap__SWIG_0(swigCPtr, this, secondBmp) : skiaviewJNI.GiCanvasBase_hasCachedBitmapSwigExplicitGiCanvasBase__SWIG_0(swigCPtr, this, secondBmp);
  }

  public boolean hasCachedBitmap() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_hasCachedBitmap__SWIG_1(swigCPtr, this) : skiaviewJNI.GiCanvasBase_hasCachedBitmapSwigExplicitGiCanvasBase__SWIG_1(swigCPtr, this);
  }

  public boolean isBufferedDrawing() {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_isBufferedDrawing(swigCPtr, this) : skiaviewJNI.GiCanvasBase_isBufferedDrawingSwigExplicitGiCanvasBase(swigCPtr, this);
  }

  public void clipBoxChanged(float x, float y, float w, float h) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_clipBoxChanged(swigCPtr, this, x, y, w, h); else skiaviewJNI.GiCanvasBase_clipBoxChangedSwigExplicitGiCanvasBase(swigCPtr, this, x, y, w, h);
  }

  public void antiAliasModeChanged(boolean antiAlias) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_antiAliasModeChanged(swigCPtr, this, antiAlias); else skiaviewJNI.GiCanvasBase_antiAliasModeChangedSwigExplicitGiCanvasBase(swigCPtr, this, antiAlias);
  }

  public boolean drawImage(String name, float xc, float yc, float w, float h, float angle) {
    return (getClass() == GiCanvasBase.class) ? skiaviewJNI.GiCanvasBase_drawImage(swigCPtr, this, name, xc, yc, w, h, angle) : skiaviewJNI.GiCanvasBase_drawImageSwigExplicitGiCanvasBase(swigCPtr, this, name, xc, yc, w, h, angle);
  }

  public void rawTextCenter(String text, float x, float y, float h) {
    if (getClass() == GiCanvasBase.class) skiaviewJNI.GiCanvasBase_rawTextCenter(swigCPtr, this, text, x, y, h); else skiaviewJNI.GiCanvasBase_rawTextCenterSwigExplicitGiCanvasBase(swigCPtr, this, text, x, y, h);
  }

}
