/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class GiColor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GiColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GiColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_GiColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setR(short value) {
    skiaviewJNI.GiColor_r_set(swigCPtr, this, value);
  }

  public short getR() {
    return skiaviewJNI.GiColor_r_get(swigCPtr, this);
  }

  public void setG(short value) {
    skiaviewJNI.GiColor_g_set(swigCPtr, this, value);
  }

  public short getG() {
    return skiaviewJNI.GiColor_g_get(swigCPtr, this);
  }

  public void setB(short value) {
    skiaviewJNI.GiColor_b_set(swigCPtr, this, value);
  }

  public short getB() {
    return skiaviewJNI.GiColor_b_get(swigCPtr, this);
  }

  public void setA(short value) {
    skiaviewJNI.GiColor_a_set(swigCPtr, this, value);
  }

  public short getA() {
    return skiaviewJNI.GiColor_a_get(swigCPtr, this);
  }

  public GiColor() {
    this(skiaviewJNI.new_GiColor__SWIG_0(), true);
  }

  public GiColor(short _r, short _g, short _b, short _a) {
    this(skiaviewJNI.new_GiColor__SWIG_1(_r, _g, _b, _a), true);
  }

  public GiColor(short _r, short _g, short _b) {
    this(skiaviewJNI.new_GiColor__SWIG_2(_r, _g, _b), true);
  }

  public GiColor(GiColor c) {
    this(skiaviewJNI.new_GiColor__SWIG_3(GiColor.getCPtr(c), c), true);
  }

  public static GiColor White() {
    return new GiColor(skiaviewJNI.GiColor_White(), true);
  }

  public static GiColor Black() {
    return new GiColor(skiaviewJNI.GiColor_Black(), true);
  }

  public static GiColor Invalid() {
    return new GiColor(skiaviewJNI.GiColor_Invalid(), true);
  }

  public int getARGB() {
    return skiaviewJNI.GiColor_getARGB(swigCPtr, this);
  }

  public void setARGB(int value) {
    skiaviewJNI.GiColor_setARGB(swigCPtr, this, value);
  }

  public void set(short _r, short _g, short _b) {
    skiaviewJNI.GiColor_set__SWIG_0(swigCPtr, this, _r, _g, _b);
  }

  public void set(short _r, short _g, short _b, short _a) {
    skiaviewJNI.GiColor_set__SWIG_1(swigCPtr, this, _r, _g, _b, _a);
  }

  public boolean isInvalid() {
    return skiaviewJNI.GiColor_isInvalid(swigCPtr, this);
  }

  public boolean equals(GiColor src) {
    return skiaviewJNI.GiColor_equals(swigCPtr, this, GiColor.getCPtr(src), src);
  }

}
