/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class GiCoreView {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GiCoreView(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GiCoreView obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_GiCoreView(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GiCoreView(GiCanvasBase canvas) {
    this(skiaviewJNI.new_GiCoreView(GiCanvasBase.getCPtr(canvas), canvas), true);
  }

  public boolean findShapeByImageId(String name) {
    return skiaviewJNI.GiCoreView_findShapeByImageId(swigCPtr, this, name);
  }

  public boolean addImageShapes(String name, int width, int height) {
    return skiaviewJNI.GiCoreView_addImageShapes(swigCPtr, this, name, width, height);
  }

  public boolean saveShapes(MgStorage s) {
    return skiaviewJNI.GiCoreView_saveShapes(swigCPtr, this, MgStorage.getCPtr(s), s);
  }

  public boolean loadShapes(MgStorage s) {
    return skiaviewJNI.GiCoreView_loadShapes(swigCPtr, this, MgStorage.getCPtr(s), s);
  }

  public int getShapeCount() {
    return skiaviewJNI.GiCoreView_getShapeCount(swigCPtr, this);
  }

  public int getRedrawCount() {
    return skiaviewJNI.GiCoreView_getRedrawCount(swigCPtr, this);
  }

  public int getChangeCount() {
    return skiaviewJNI.GiCoreView_getChangeCount(swigCPtr, this);
  }

  public int addTestingShapes() {
    return skiaviewJNI.GiCoreView_addTestingShapes(swigCPtr, this);
  }

  public int getWidth() {
    return skiaviewJNI.GiCoreView_getWidth(swigCPtr, this);
  }

  public int getHeight() {
    return skiaviewJNI.GiCoreView_getHeight(swigCPtr, this);
  }

  public boolean onSize(int width, int height) {
    return skiaviewJNI.GiCoreView_onSize(swigCPtr, this, width, height);
  }

  public boolean onDraw(GiCanvasBase canvas) {
    return skiaviewJNI.GiCoreView_onDraw(swigCPtr, this, GiCanvasBase.getCPtr(canvas), canvas);
  }

  public boolean onDynDraw(GiCanvasBase canvas) {
    return skiaviewJNI.GiCoreView_onDynDraw(swigCPtr, this, GiCanvasBase.getCPtr(canvas), canvas);
  }

  public String getCommandName() {
    return skiaviewJNI.GiCoreView_getCommandName(swigCPtr, this);
  }

  public boolean setCommandName(String name) {
    return skiaviewJNI.GiCoreView_setCommandName(swigCPtr, this, name);
  }

  public void doContextAction(int action) {
    skiaviewJNI.GiCoreView_doContextAction(swigCPtr, this, action);
  }

  public boolean onGesture(GiGestureType gestureType, GiGestureState gestureState, int fingerCount, float x1, float y1, float x2, float y2) {
    return skiaviewJNI.GiCoreView_onGesture(swigCPtr, this, gestureType.swigValue(), gestureState.swigValue(), fingerCount, x1, y1, x2, y2);
  }

  public GiContext getCurrentContext(boolean forChange) {
    return new GiContext(skiaviewJNI.GiCoreView_getCurrentContext(swigCPtr, this, forChange), false);
  }

  public void applyContext(GiContext ctx, int mask, int apply) {
    skiaviewJNI.GiCoreView_applyContext(swigCPtr, this, GiContext.getCPtr(ctx), ctx, mask, apply);
  }

  public void setZoomFeature(int mask) {
    skiaviewJNI.GiCoreView_setZoomFeature(swigCPtr, this, mask);
  }

  public int getDimensions(Floats vars, Chars types) {
    return skiaviewJNI.GiCoreView_getDimensions(swigCPtr, this, Floats.getCPtr(vars), vars, Chars.getCPtr(types), types);
  }

}
