/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public final class GiGestureState {
  public final static GiGestureState kGestureCancel = new GiGestureState("kGestureCancel", skiaviewJNI.kGestureCancel_get());
  public final static GiGestureState kGestureBegan = new GiGestureState("kGestureBegan");
  public final static GiGestureState kGestureMoved = new GiGestureState("kGestureMoved");
  public final static GiGestureState kGestureEnded = new GiGestureState("kGestureEnded");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static GiGestureState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + GiGestureState.class + " with value " + swigValue);
  }

  private GiGestureState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private GiGestureState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private GiGestureState(String swigName, GiGestureState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static GiGestureState[] swigValues = { kGestureCancel, kGestureBegan, kGestureMoved, kGestureEnded };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

