/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class Ints {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Ints(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ints obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_Ints(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Ints(int n) {
    this(skiaviewJNI.new_Ints(n), true);
  }

  public int count() {
    return skiaviewJNI.Ints_count(swigCPtr, this);
  }

  public int get(int index) {
    return skiaviewJNI.Ints_get(swigCPtr, this, index);
  }

  public void set(int index, int value) {
    skiaviewJNI.Ints_set(swigCPtr, this, index, value);
  }

}
