/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MATRIX_2D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MATRIX_2D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MATRIX_2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_MATRIX_2D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM11(float value) {
    skiaviewJNI.MATRIX_2D_m11_set(swigCPtr, this, value);
  }

  public float getM11() {
    return skiaviewJNI.MATRIX_2D_m11_get(swigCPtr, this);
  }

  public void setM12(float value) {
    skiaviewJNI.MATRIX_2D_m12_set(swigCPtr, this, value);
  }

  public float getM12() {
    return skiaviewJNI.MATRIX_2D_m12_get(swigCPtr, this);
  }

  public void setM21(float value) {
    skiaviewJNI.MATRIX_2D_m21_set(swigCPtr, this, value);
  }

  public float getM21() {
    return skiaviewJNI.MATRIX_2D_m21_get(swigCPtr, this);
  }

  public void setM22(float value) {
    skiaviewJNI.MATRIX_2D_m22_set(swigCPtr, this, value);
  }

  public float getM22() {
    return skiaviewJNI.MATRIX_2D_m22_get(swigCPtr, this);
  }

  public void setDx(float value) {
    skiaviewJNI.MATRIX_2D_dx_set(swigCPtr, this, value);
  }

  public float getDx() {
    return skiaviewJNI.MATRIX_2D_dx_get(swigCPtr, this);
  }

  public void setDy(float value) {
    skiaviewJNI.MATRIX_2D_dy_set(swigCPtr, this, value);
  }

  public float getDy() {
    return skiaviewJNI.MATRIX_2D_dy_get(swigCPtr, this);
  }

  public MATRIX_2D() {
    this(skiaviewJNI.new_MATRIX_2D(), true);
  }

}
