/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgBaseLines extends MgBaseShape {
  private long swigCPtr;

  protected MgBaseLines(long cPtr, boolean cMemoryOwn) {
    super(skiaviewJNI.MgBaseLines_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgBaseLines obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static int Type() {
    return skiaviewJNI.MgBaseLines_Type();
  }

  public void setClosed(boolean closed) {
    skiaviewJNI.MgBaseLines_setClosed(swigCPtr, this, closed);
  }

  public Point2d endPoint() {
    return new Point2d(skiaviewJNI.MgBaseLines_endPoint(swigCPtr, this), true);
  }

  public boolean resize(int count) {
    return skiaviewJNI.MgBaseLines_resize(swigCPtr, this, count);
  }

  public boolean addPoint(Point2d pt) {
    return skiaviewJNI.MgBaseLines_addPoint(swigCPtr, this, Point2d.getCPtr(pt), pt);
  }

  public boolean insertPoint(int segment, Point2d pt) {
    return skiaviewJNI.MgBaseLines_insertPoint(swigCPtr, this, segment, Point2d.getCPtr(pt), pt);
  }

  public boolean removePoint(int index) {
    return skiaviewJNI.MgBaseLines_removePoint(swigCPtr, this, index);
  }

}
