/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgImageShape extends MgBaseRect {
  private long swigCPtr;

  protected MgImageShape(long cPtr, boolean cMemoryOwn) {
    super(skiaviewJNI.MgImageShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgImageShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_MgImageShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MgImageShape() {
    this(skiaviewJNI.new_MgImageShape(), true);
  }

  public static MgImageShape create() {
    long cPtr = skiaviewJNI.MgImageShape_create();
    return (cPtr == 0) ? null : new MgImageShape(cPtr, false);
  }

  public static int Type() {
    return skiaviewJNI.MgImageShape_Type();
  }

  public String getName() {
    return skiaviewJNI.MgImageShape_getName(swigCPtr, this);
  }

  public void setName(String name) {
    skiaviewJNI.MgImageShape_setName(swigCPtr, this, name);
  }

  public static MgShape findShapeByImageID(MgShapes shapes, String name) {
    long cPtr = skiaviewJNI.MgImageShape_findShapeByImageID(MgShapes.getCPtr(shapes), shapes, name);
    return (cPtr == 0) ? null : new MgShape(cPtr, false);
  }

}
