/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgLine extends MgBaseShape {
  private long swigCPtr;

  protected MgLine(long cPtr, boolean cMemoryOwn) {
    super(skiaviewJNI.MgLine_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgLine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_MgLine(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MgLine() {
    this(skiaviewJNI.new_MgLine(), true);
  }

  public static MgLine create() {
    long cPtr = skiaviewJNI.MgLine_create();
    return (cPtr == 0) ? null : new MgLine(cPtr, false);
  }

  public static int Type() {
    return skiaviewJNI.MgLine_Type();
  }

  public Point2d startPoint() {
    return new Point2d(skiaviewJNI.MgLine_startPoint(swigCPtr, this), false);
  }

  public Point2d endPoint() {
    return new Point2d(skiaviewJNI.MgLine_endPoint(swigCPtr, this), false);
  }

  public Point2d center() {
    return new Point2d(skiaviewJNI.MgLine_center(swigCPtr, this), true);
  }

  public float length() {
    return skiaviewJNI.MgLine_length(swigCPtr, this);
  }

  public float angle() {
    return skiaviewJNI.MgLine_angle(swigCPtr, this);
  }

  public void setStartPoint(Point2d pt) {
    skiaviewJNI.MgLine_setStartPoint(swigCPtr, this, Point2d.getCPtr(pt), pt);
  }

  public void setEndPoint(Point2d pt) {
    skiaviewJNI.MgLine_setEndPoint(swigCPtr, this, Point2d.getCPtr(pt), pt);
  }

}
