/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgLines extends MgBaseLines {
  private long swigCPtr;

  protected MgLines(long cPtr, boolean cMemoryOwn) {
    super(skiaviewJNI.MgLines_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgLines obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_MgLines(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MgLines() {
    this(skiaviewJNI.new_MgLines(), true);
  }

  public static MgLines create() {
    long cPtr = skiaviewJNI.MgLines_create();
    return (cPtr == 0) ? null : new MgLines(cPtr, false);
  }

  public static int Type() {
    return skiaviewJNI.MgLines_Type();
  }

}
