/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class MgRoundRect extends MgBaseRect {
  private long swigCPtr;

  protected MgRoundRect(long cPtr, boolean cMemoryOwn) {
    super(skiaviewJNI.MgRoundRect_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgRoundRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_MgRoundRect(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MgRoundRect() {
    this(skiaviewJNI.new_MgRoundRect(), true);
  }

  public static MgRoundRect create() {
    long cPtr = skiaviewJNI.MgRoundRect_create();
    return (cPtr == 0) ? null : new MgRoundRect(cPtr, false);
  }

  public static int Type() {
    return skiaviewJNI.MgRoundRect_Type();
  }

  public float getRadiusX() {
    return skiaviewJNI.MgRoundRect_getRadiusX(swigCPtr, this);
  }

  public float getRadiusY() {
    return skiaviewJNI.MgRoundRect_getRadiusY(swigCPtr, this);
  }

  public void setRadius(float rx, float ry) {
    skiaviewJNI.MgRoundRect_setRadius__SWIG_0(swigCPtr, this, rx, ry);
  }

  public void setRadius(float rx) {
    skiaviewJNI.MgRoundRect_setRadius__SWIG_1(swigCPtr, this, rx);
  }

}
