/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.jni;

public class POINT_2D {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected POINT_2D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(POINT_2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        skiaviewJNI.delete_POINT_2D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    skiaviewJNI.POINT_2D_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return skiaviewJNI.POINT_2D_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    skiaviewJNI.POINT_2D_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return skiaviewJNI.POINT_2D_y_get(swigCPtr, this);
  }

  public POINT_2D() {
    this(skiaviewJNI.new_POINT_2D(), true);
  }

}
